<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import type { DashboardStats } from '../../types'
import AppIcon from '../../components/base/AppIcon.vue'
import ActivityTimeline from '../../components/feedback/ActivityTimeline.vue'
const router = useRouter(); const stats = ref<DashboardStats>({ total: 0, perwira: 0, bintara: 0, tamtama: 0 }); const loading = ref(true); const activities = ref<Array<{ id: number; type: string; title: string; description: string; performedBy: string; createdAt: string }>>([])
function cardIcon(label: string) { return ({ 'Total Personel': 'personnel', Perwira: 'shield', Bintara: 'badge', Tamtama: 'user-check', Siap: 'check', 'Belum Siap': 'alert' } as Record<string, string>)[label] || 'shield' }
onMounted(async () => { try { stats.value = await window.api.getPersonnelSummary(); activities.value = await window.api.getLatestActivities(10) } finally { loading.value = false } })
</script>
<template><div class="page-heading"><div><h2>Selamat Datang</h2><p>Ringkasan data personel dan kesiapan satuan.</p></div><div class="heading-actions"><button class="outline" @click="router.push('/import')"><AppIcon name="import" :size="15" /> Import Data</button><button class="primary" @click="router.push('/personnel/create')"><AppIcon name="personnel" :size="15" /> Tambah Personel</button></div></div><section class="stats"><article v-for="card in [{label:'Total Personel',value:stats.total},{label:'Perwira',value:stats.perwira},{label:'Bintara',value:stats.bintara},{label:'Tamtama',value:stats.tamtama},{label:'Siap',value:'—'},{label:'Belum Siap',value:'—'}]" :key="card.label" class="stat-card"><span class="stat-icon"><AppIcon :name="cardIcon(card.label)" :size="18" /></span><strong>{{ loading ? '—' : card.value }}</strong><b>{{ card.label }}</b><small>Data tersimpan lokal</small></article></section><section class="dashboard-grid"><article class="panel activity"><div class="panel-head"><h3>Aktivitas Terkini</h3><span class="badge gold">Live</span></div><ActivityTimeline :activities="activities" /><button class="activity-view-all" @click="router.push('/activity')">Lihat Semua <span>›</span></button></article><aside class="right-stack"><article class="panel quick"><h3>Aksi Cepat</h3><button @click="router.push('/personnel/create')"><AppIcon name="personnel" :size="16" /> Tambah Personel Baru <span>›</span></button><button @click="router.push('/import')"><AppIcon name="import" :size="16" /> Import Data Excel <span>›</span></button><button @click="router.push('/reports')"><AppIcon name="reports" :size="16" /> Buat Laporan Kekuatan <span>›</span></button></article><article class="readiness"><span>KEKUATAN SATUAN</span><strong>— <small>Siap Tempur</small></strong><div class="progress"><i /></div><footer><small>Data status belum tersedia</small></footer></article></aside></section></template>
