PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS "User" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "username" TEXT NOT NULL UNIQUE, "passwordHash" TEXT NOT NULL, "role" TEXT NOT NULL DEFAULT 'OPERATOR', "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL);
CREATE TABLE IF NOT EXISTS "Setting" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "namaSatgas" TEXT, "namaKesatuan" TEXT, "lokasi" TEXT, "komandan" TEXT, "nrpKomandan" TEXT, "emailSatuan" TEXT, "logoPath" TEXT, "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "Personnel" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "nrp" TEXT NOT NULL, "urut" INTEGER, "nama" TEXT NOT NULL, "pktKorp" TEXT, "pangkat" TEXT, "kodePangkat" TEXT, "kategoriPangkat" TEXT, "korps" TEXT, "jabatan" TEXT, "jabDalamLat" TEXT, "divisi" TEXT, "brigade" TEXT, "kelompok" TEXT, "satminkal" TEXT, "bagKompi" TEXT, "ton" TEXT, "ru" TEXT, "mako" TEXT, "satuan" TEXT, "subSatuan" TEXT, "tempatLahir" TEXT, "tanggalLahir" DATETIME, "tmtPangkat" DATETIME, "tmtJabatan" DATETIME, "kategoriPersonel" TEXT, "sukuBangsa" TEXT, "statusKeluarga" TEXT, "agama" TEXT, "golonganDarah" TEXT, "noSkep" TEXT, "namaPasangan" TEXT, "jumlahAnak" INTEGER, "alamat" TEXT, "nik" TEXT, "noKK" TEXT, "npwp" TEXT, "bpjs" TEXT, "asabri" TEXT, "keterangan" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "PersonnelDocument" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "personnelId" INTEGER NOT NULL, "namaFile" TEXT NOT NULL, "filePath" TEXT NOT NULL, "mimeType" TEXT, "ukuranBytes" INTEGER, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("personnelId") REFERENCES "Personnel" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE IF NOT EXISTS "PersonnelStatus" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "personnelId" INTEGER NOT NULL, "tanggal" DATETIME NOT NULL, "statusAbsen" TEXT, "statusKesiapan" TEXT, "statusBP" TEXT, "keterangan" TEXT, FOREIGN KEY ("personnelId") REFERENCES "Personnel" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE IF NOT EXISTS "PersonnelAssignment" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "personnelId" INTEGER NOT NULL, "satuan" TEXT, "subSatuan" TEXT, "jabatan" TEXT, "jenisJabatan" TEXT, "tanggalMulai" DATETIME, "tanggalSelesai" DATETIME, "aktif" BOOLEAN NOT NULL DEFAULT 1, FOREIGN KEY ("personnelId") REFERENCES "Personnel" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE IF NOT EXISTS "ImportBatch" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "fileName" TEXT NOT NULL, "importedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "totalRows" INTEGER NOT NULL DEFAULT 0, "successRows" INTEGER NOT NULL DEFAULT 0, "failedRows" INTEGER NOT NULL DEFAULT 0, "status" TEXT NOT NULL DEFAULT 'PROCESSING');
CREATE TABLE IF NOT EXISTS "BackupHistory" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "fileName" TEXT NOT NULL, "filePath" TEXT NOT NULL, "ukuranBytes" INTEGER, "status" TEXT NOT NULL DEFAULT 'BERHASIL', "error" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "ReportGeneration" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "jenis" TEXT NOT NULL, "periode" TEXT, "fileName" TEXT, "filePath" TEXT, "status" TEXT NOT NULL DEFAULT 'PROCESSING', "error" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "ActivityLog" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "type" TEXT NOT NULL, "title" TEXT NOT NULL, "description" TEXT NOT NULL, "performedBy" TEXT NOT NULL, "metadata" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE INDEX IF NOT EXISTS "Personnel_nrp_idx" ON "Personnel"("nrp");
CREATE INDEX IF NOT EXISTS "Personnel_nama_idx" ON "Personnel"("nama");
CREATE INDEX IF NOT EXISTS "PersonnelDocument_personnelId_idx" ON "PersonnelDocument"("personnelId");
CREATE UNIQUE INDEX IF NOT EXISTS "PersonnelStatus_personnelId_tanggal_key" ON "PersonnelStatus"("personnelId", "tanggal");
CREATE INDEX IF NOT EXISTS "PersonnelStatus_tanggal_idx" ON "PersonnelStatus"("tanggal");
CREATE INDEX IF NOT EXISTS "PersonnelAssignment_personnelId_aktif_idx" ON "PersonnelAssignment"("personnelId", "aktif");
CREATE INDEX IF NOT EXISTS "ActivityLog_createdAt_idx" ON "ActivityLog"("createdAt");
CREATE INDEX IF NOT EXISTS "ActivityLog_type_idx" ON "ActivityLog"("type");
