<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import AppIcon from '../../components/base/AppIcon.vue'
import { useToast } from '../../composables/useToast'
const router = useRouter(); const { showToast } = useToast(); const saving = ref(false)
const form = ref<Record<string, any>>({ nama:'', pktKorp:'', pangkat:'', kodePangkat:'', nrp:'', korps:'', jabatan:'', jabDalamLat:'', divisi:'', brigade:'', kelompok:'', satminkal:'', bagKompi:'', ton:'', ru:'', keterangan:'' })
const ranks = ['JENDERAL','LETJEN','MAYJEN','BRIGJEN','KOLONEL','LETKOL','MAYOR','KAPTEN','LETTU','LETDA','PELTU','PELDA','SERMA','SERKA','SERTU','SERDA','KOPKA','KOPTU','KOPDA','PRAKA','PRATU','PRADA']
const requiredFields = ['nama','pktKorp','pangkat','kodePangkat','nrp','korps','jabatan','jabDalamLat','divisi','brigade','kelompok','satminkal','bagKompi']
async function submit() { const missing = requiredFields.find((field) => !String(form.value[field] || '').trim()); if (missing) { showToast('Lengkapi seluruh field wajib Data Pelaku.', 'error'); return }; saving.value = true; try { await window.api.createPersonnel({ ...form.value }); showToast('Data pelaku berhasil disimpan.'); router.push('/personnel') } catch { showToast('Data pelaku gagal disimpan.', 'error') } finally { saving.value = false } }
</script>
<template>
  <div class="module-title"><div><h2>Tambah Data Pelaku</h2><p>Isi data sesuai struktur Data Pelaku.</p></div><button class="outline" @click="router.back()">‹ Kembali</button></div>
  <form class="personnel-form pelaku-form" @submit.prevent="submit"><section class="panel form-panel"><h3><AppIcon name="data" :size="15" /> DATA PELAKU</h3><div class="form-grid"><label>NAMA *<input v-model="form.nama" placeholder="ADE RONY WIJAYA, S.E.,M.M." required /></label><label>PKT/KORP *<input v-model="form.pktKorp" placeholder="LETKOL INF" required /></label><label>PKT *<select v-model="form.pangkat" required><option value="">Pilih pangkat</option><option v-for="rank in ranks" :key="rank">{{ rank }}</option></select></label><label>PKT1 *<input v-model="form.kodePangkat" placeholder="83" required /></label><label>NRP *<input v-model="form.nrp" class="mono" placeholder="11980053970877" inputmode="numeric" required /></label><label>KORPS *<input v-model="form.korps" placeholder="INF" required /></label><label>JAB ORGANIK *<input v-model="form.jabatan" placeholder="DANBRIGIF PARA RAIDER 17" required /></label><label>JAB DLM LAT *<input v-model="form.jabDalamLat" placeholder="DANBTP" required /></label><label>DIVISI *<input v-model="form.divisi" placeholder="DIVISI 1 KOSTRAD" required /></label><label>BRIGADE *<input v-model="form.brigade" placeholder="BRIGIF PR 17" required /></label><label>KELOMPOK *<input v-model="form.kelompok" placeholder="MABRIGIF PR 17" required /></label><label>SATMINKAL *<input v-model="form.satminkal" placeholder="1" required /></label><label>BAG/KOMPI *<input v-model="form.bagKompi" placeholder="DENMA BRIGIF PR 8" required /></label><label>TON<input v-model="form.ton" placeholder="MA & DENMA BRIGIF PR 18" /></label><label>RU<input v-model="form.ru" placeholder="—" /></label><label class="full-field">KET<input v-model="form.keterangan" placeholder="Keterangan tambahan" /></label></div></section><div class="form-actions"><button type="button" class="outline" @click="router.back()">Batal</button><button type="submit" class="primary" :disabled="saving"><AppIcon name="save" :size="15" /> {{ saving ? 'Menyimpan...' : 'Simpan Data' }}</button></div></form>
</template>
